Sudoku/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using Sudoku.Areas.HelpPage.ModelDescriptions;

namespace Sudoku.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

Sudoku/Models/Cell.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Sudoku.Models
{
    public class Cell
    {
        public int Id { get; set; }

        public string ColName { get; set; }
    }
}

Sudoku/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using Sudoku.Areas.HelpPage.ModelDescriptions;
using Sudoku.Areas.HelpPage.Models;

namespace Sudoku.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

Sudoku/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Http;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using SudocuData.Entities;
using SudocuServices.Services;
using System.Threading.Tasks;
using Newtonsoft.Json;
using System.Web.Http.Results;
using Sudoku.Models;
using System.Web;

namespace Sudoku.Controllers
{
    [RoutePrefix("api/main")]
    public class MainController : ApiController
    {
        private INumberService _numService = new NumberService();
        private NumberContext db = new NumberContext();        
                
        //[HttpPost]
        //public IHttpActionResult Post( int level)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return BadRequest(ModelState);
        //    }
        //    var request = HttpContext.Current.Items["MS_HttpRequestMessage"] as HttpRequestMessage;
        //    var httpContext = (HttpContextWrapper)request.Properties["MS_HttpContext"];

        //    var response = _numService.Load(level);
        //    db.SaveChanges();

        //    return Ok();
        //}

        [HttpPut]
        [Route("OpenCell")]
        public IHttpActionResult OpenCell([FromBody] Cell cells)
        {
            int n = _numService.Open(cells.Id, cells.ColName);
            if (n != 0)
                return Ok(n);
            else
                return NotFound();
        }

        [HttpPut]
        [Route("Verify")]
        public IHttpActionResult Verify([FromBody] List<NumberResponse> data)
        {
            bool eq = _numService.Verify(data);
            return Ok(eq);
        }

    }
}

Sudoku/Controllers/MainViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Net.Http.Headers;
using System.Net.Http;
using SudocuData.Entities;
using SudocuServices.Services;



namespace Sudoku.Controllers
{
    public class MainViewController : Controller
    {
        private INumberService _numService = new NumberService();
        private NumberContext db = new NumberContext();

        [HttpGet]
        public ActionResult Index(int level)
        {
            var data = _numService.Load(level);
            return View(data); 
        }

       
    }
}

Sudoku/Views/Home/Index.cshtml
{
  Layout = null;
}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

</head>
<body>

 </body>
</html>

Sudoku/Views/MainView/Index.cshtml
@using SudocuData.Entities;
@model List<NumberResponse>
@{
    ViewBag.Title = "Main";
}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Product App</title>
   
    <script type="text/javascript" src="~/Scripts/jquery-3.4.0.js"></script>
    <script type="text/javascript" src="~/Scripts/jcook.js"></script>
    <script>
        var selectVal = '';
        var selectId = 0;
        var arr = [];

        $('.row').ready(function () {

            var lev = Number($("#level").text());
            addArrayToCookie(lev); //записываем уровень в куки

            //изменение цвета введенных значений
            $('input').change(function () {
                  this.style.color = 'blue';
                
            });

            //блокировка от изменения значений по умолчанию
            $('input').hover(function () {
                if (this.value != null && this.value != "" && this.style.color != "blue" && this.style.color != "red") {
                    $(this).attr('readonly', 'readonly');
                }
                else {
                    $(this).removeAttr('readonly', 'readonly');
                }
            });
            //стилевые параметры ячейки в фокусе
            $('input').focus(function () {
                if (this.value == null || this.value == "") {
                    this.style.backgroundColor = '#cec8c8';
                    selectVal = this.getAttribute('id');
                    selectId = this.parentElement.parentElement.children[0].children[0].value;

                }
            });

            $('input').blur(function () {
                if (!$('#opencell').is(":hover")) {
                    this.style.backgroundColor = '';
                }
                if (this.value && isNaN(this.value)) {
                    // показать ошибку
                    this.style.color = 'red';
                    error.innerHTML = 'Недопустимое значение. Введите цифру.';
                }
                var regexp = /^[1-9]{1}$/;
                if (this.value && !regexp.exec(this.value)) {
                    this.style.color = 'red';
                    error.innerHTML = 'Недопустимое значение. Введите цифру от 1 до 9';
                }

                else {
                    this.style.borderColor = '';
                    error.innerHTML = '';
                }
               
            });
        })

    </script>

</head>
<body>

    <div>
        <h2>СУДОКУ</h2>
        <ul id="maintable" />
    </div>
    <div>
        <!--<input type="button" value="Search" onclick="find();" />-->
        <p />
    </div>

    <div class="tables">
        <table id="tserv">
            @foreach (var item in Model)
            {
            <tr class="row">
                <td hidden class="range1">
                    <input id="id" value=@item.Id>
                </td>
                <td class="range1">
                    <input id="num1" name="tt" required pattern="[1-9]" value=@item.Num1>
                </td>
                <td class="range1">
                    <input id="num2" value=@item.Num2>
                </td>
                <td class="range1">
                    <input id="num3" value=@item.Num3>
                </td>
                <td class="range2">
                    <input id="num4" value=@item.Num4>
                </td>
                <td class="range2">
                    <input id="num5" value=@item.Num5>
                </td>
                <td class="range2">
                    <input id="num6" value=@item.Num6>
                </td>
                <td class="range1">
                    <input id="num7" value=@item.Num7>
                </td>
                <td class="range1">
                    <input id="num8" value=@item.Num8>
                </td>
                <td class="range1">
                    <input id="num9" value=@item.Num9>
                </td>

            </tr>
            }
        </table>
        <div class="buttons">
            <div class="level">
                <label id="lab1">Уровень сложности:  <span id="level">@Model.Select(x => x.Level).First()</span></label>
                
            </div>
            <button id="reload" data-id={GameId} data-action="load">Новая игра</button>
            <button id="opencell" data-id={GameId} data-action="open">Открыть ячейку</button>
            <button id="check" data-id={GameId} data-action="verify">Проверить</button>
            <div id="error"></div>
            <div id="result"></div>
        </div>
    </div>

    <script type="text/javascript">
        
        function getLevel() {
            var arr = readArrayFromCookie();

            for (var i = 1; i < 6; i++) {
                // var rand = Math.floor(Math.random() * 5); - если хотим рандомно

                //если в куки нет этого числа, возвращаем его
                if (!arr.includes(i)) {
                    return i;
                }
            }
            deleteCookie();
            alert("Все этапы игры пройдены. Начните заново.");
            return 1;
        };

        //перезапуск
        $(function () {
            $('#reload').click(function (e) {
                var newLevel = getLevel();
                console.log(newLevel);
                location.href = `/MainView/Index/${newLevel}`  
                
            });
        });

        //открыть ячейку
        $(function () {
            $('#opencell').click(function (e) {
                console.log(selectVal);
                var level = $("#level").text();
                var cell = {
                    Id: selectId,
                    ColName: selectVal
                }
                $.ajax({
                    type: 'PUT',
                    url: '/api/Main/OpenCell',
                    contentType: 'application/json; charset=utf-8',
                    data: JSON.stringify(cell),
                    success: function (n) {
                        var input = $('input[id=' + selectVal + ']')
                        var input2 = $('input:focus');
                        var num = selectId - (level == 1 ? 1 : (level - 1) * 9 + 1);
                        input[num].value = n; 
                        input[num].style.backgroundColor = '';
                        input[num].style.color = 'inherit';
                    },
                    fail: function (data) {
                        alert("Unknown error");
                    }
                });
                console.log(level);
            });
        });

        //проверить
        $(function () {
            $('#check').click(function (e) {
                e.preventDefault();
                var table = $('#tserv');
                var rows = table.children().children();
                                
                var listdata = [];
                for (var i = 0; i < rows.length; i++) {
                     var tr = $(rows[i]).children().children();
                
                var response = {
                    Id: tr[0].value,
                    Level: $("#level").text(),
                    Num1: tr[1].value,
                    Num2: tr[2].value,
                    Num3: tr[3].value,
                    Num4: tr[4].value,
                    Num5: tr[5].value,
                    Num6: tr[6].value,
                    Num7: tr[7].value,
                    Num8: tr[8].value,
                    Num9: tr[9].value
                    }
                   
                    listdata.push(response);
                }

                console.log(listdata);

               $.ajax({
                    type: 'PUT',
                    url: '/api/Main/Verify',
                    contentType: 'application/json; charset=utf-8',
                    data: JSON.stringify(listdata),
                    success: function (data) {
                        if (data) {
                            result.style.color = 'forestgreen';
                            result.innerHTML = 'Поздравляю Вас! Вы правильно решили Судоку.';
                        }
                        else {
                            result.style.color = 'red';
                            result.innerHTML = 'В решении есть ошибки.';
                        }
                    },
                    fail: function (data) {
                        alert("Unknown error");
                    }
                });
            });
        })
    </script>
   
</body>
</html>

Sudoku/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "MainView", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                   <!-- <li>@Html.ActionLink("Домашняя страница", "Index", "MainView", new { area = "" }, null)</li> -->
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>